name: Build

on:
  workflow_call:

jobs:
  Android:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false && (contains(github.event.pull_request.labels.*.name, 'KMP') || contains(github.event.pull_request.labels.*.name, 'Android'))) }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew :androidApp:assemble

#  Desktop:
 #   if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false && (contains(github.event.pull_request.labels.*.name, 'KMP') || contains(github.event.pull_request.labels.*.name, 'Desktop'))) }}
  #  runs-on: ubuntu-latest

   # steps:
    #  - uses: actions/checkout@v3

     # - uses: actions/setup-java@v3
      #  with:
       #   distribution: "adopt"
        #  java-version: "11"

      #- name: Setup Gradle
       # uses: gradle/gradle-build-action@v2

      #- run: ./gradlew :desktopApp:assemble

  iOS:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.draft == false && (contains(github.event.pull_request.labels.*.name, 'KMP') || contains(github.event.pull_request.labels.*.name, 'iOS'))) }}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "11"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - run: ./gradlew :shared:generateDummyFramework

      - name: Set up cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: Install Dependencies
        run: |
          cd iosApp
          pod install --verbose

      - run: xcodebuild build -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose