name: Tests

on:
  workflow_call:
    inputs:
      shouldRunKmp:
        required: true
        type: string
      shouldRunAndroid:
        required: true
        type: string
      shouldRunIos:
        required: true
        type: string

jobs:
  Android:
    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunAndroid == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-setup

      - run: ./gradlew clean testDebug -p androidApp/

  iOS:
    #    if: ${{ inputs.shouldRunKmp == 'true' || inputs.shouldRunIos == 'true' }}
    if: false
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-setup

      - name: iOS set up
        uses: ./.github/actions/ios-setup

      - run: xcodebuild build test -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          path: "/Users/runner/Library/Developer/Xcode/DerivedData/*"

  KMP-Android:
    if: ${{ inputs.shouldRunKmp == 'true'}}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-setup

      - run: ./gradlew clean testDebugUnitTest -p shared/

  KMP-iOS:
    if: ${{ inputs.shouldRunKmp == 'true'}}
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Job set up
        uses: ./.github/actions/job-setup

      - run: if [[ $(uname -m) == 'arm64' ]]; then ./gradlew clean iosSimulatorArm64Test -p shared/; else ./gradlew clean iosX64Test -p shared/; fi